##### new runtime
# [START gae_flex_storage_yaml]
runtime: nodejs
env: flex

# env_variables:
#   GOOGLE_CLOUD_PROJECT: nodejsangularname
#   GCLOUD_STORAGE_BUCKET: nodejsangularname.appspot.com
# [END gae_flex_storage_yaml]